### ISSUE TITLE
Add "hostname" directive

### ISSUE THREAD

**Issue by sofar** [clearlinux/clr-cloud-init#1]
```hostname: [name:string]```

writes 'name' to /etc/hostname, calls `hostname name` to set it. This option is supported by the CoreOS version. The reference implementation uses "set_hostname" but that's not as clear or logical.

**Comment by devimc** [comment]
fixed using **hostnamectl set-hostname**
e304dde92df329e93e7093a18dac62308fad6dad

**Comment by sofar** [comment]
We should also have one for cloud-config data as well, not just openstack json metadata.

**Comment by devimc** [comment]
fixed commit 0be3c8ebf501eeee2ad120fbbf308739fe923c31
