### ISSUE TITLE
should use private tmp

### ISSUE THREAD

**Issue by sofar** [clearlinux/clr-cloud-init#10]
clr-cloud-init should use a mount namespace to shield mounting the config-drive in a world-readable fashion. We can use PrivateTmp=yes in the systemd unit file to do this, trivially, which will make it inaccessible elsewhere.

**Comment by devimc** [comment]
Fixed [f666061e94d2c8055aa90eb220d57957dbf6f0ee](https://github.com/clearlinux/clr-cloud-init/commit/f666061e94d2c8055aa90eb220d57957dbf6f0ee)
