### ISSUE TITLE
sudo lines should auto-prepend username.

### ISSUE THREAD

**Issue by sofar** [clearlinux/clr-cloud-init#11]
```
users:
  - name: ciao
    sudo: ciao ALL=(ALL) NOPASSWD:ALL
```

the above snipplet doesn't work on fedora or ubuntu, but is the format that clr-cloud-init requires. This is conflicting and difficult for users. We should adopt the method of the other implementations and auto-prepend the username in the sudo line.

**Comment by devimc** [comment]
fixed [a102bba2584692a19ff9fd39089f4e6d1802693e](https://github.com/clearlinux/clr-cloud-init/commit/a102bba2584692a19ff9fd39089f4e6d1802693e)
