### ISSUE TITLE
Document openstack metadata API

### ISSUE THREAD

**Issue by sofar** [clearlinux/clr-cloud-init#2]
Just like cloud-config.5, we should have a man page documenting the format and API used by the openstack metadata code.

**Comment by sofar** [comment]
This is becoming urgent. I have no documentation about what cloud-init does by default at this point. Or when config-drive is read automatically, etc.

**Comment by devimc** [comment]
Fixed [08781db9547535b8118b34078e8d670a535c8681](https://github.com/clearlinux/clr-cloud-init/commit/08781db9547535b8118b34078e8d670a535c8681)
